//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDK
    {
        public int MaPDK { get; set; }
        public string MSSV { get; set; }
        public string MaNV { get; set; }
        public string Khu { get; set; }
        public string MaPhong { get; set; }
        public string HocKi { get; set; }
        public string NamHoc { get; set; }
        public System.DateTime NgayGioDK { get; set; }
        public byte ThoiHan { get; set; }
        public System.DateTime NgayBD { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
