//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.NGUOITHANs = new HashSet<NGUOITHAN>();
            this.PHIEUDKs = new HashSet<PHIEUDK>();
        }
    
        public string MSSV { get; set; }
        public string MaLop { get; set; }
        public string DienSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<bool> Phai { get; set; }
        public Nullable<System.DateTime> NgSinh { get; set; }
        public string CMND { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string BHYT { get; set; }
        public string QueQuan { get; set; }
        public string AnhChanDung { get; set; }
    
        public virtual DIENSV DIENSV1 { get; set; }
        public virtual LOP LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOITHAN> NGUOITHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDK> PHIEUDKs { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
